services:
  - type: web
    name: scraper-backend
    runtime: node
    plan: free
    branch: main
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "node src/server.js"
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
    buildFilter:
      paths:
      - backend/**/*
    healthCheckPath: /health