services:
  - type: web
    name: scraper-backend
    runtime: node
    plan: free
    branch: main
    rootDir: backend
    healthCheckPath: /health
    buildCommand: "npm install"
    startCommand: "node src/server.js"
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
    buildpacks:
      - url: https://github.com/render-examples/puppeteer-chromium